var div1 = document.getElementById('div1');
var div2 = document.getElementById('div2');
var div3 = document.getElementById('div3');
var div4 = document.getElementById('div4');
var div5 = document.getElementById('div5');
var div6 = document.getElementById('div6');
var div7 = document.getElementById('div7');
var div8 = document.getElementById('div8');
var div9 = document.getElementById('div9');
var div10 = document.getElementById('div10');
var b = 2;
var a;
a = b++;
div1.textContent = "a=b++ : a = " + a + " b = " + b;
b = 2;
a = ++b;
div2.textContent = "a=++b : a = " + a + " b = " + b;
b = 2;
a = b--;
div3.textContent = "a=b-- : a = " + a + " b = " + b;
b = 2;
a = 0;
a = --b;
div4.textContent = "a=--b : a = " + a + " b = " + b;
b = 2;
a = 0;
a += b++;
div5.textContent = "a+=b++ : a = " + a + " b = " + b;
b = 2;
a = 1;
a += ++b;
div6.textContent = "a+=++b : a = " + a + " b = " + b;
b = 2;
a = 1;
a -= b++;
div7.textContent = "a-=b++ : a = " + a + " b = " + b;
b = 2;
a = 1;
a -= ++b;
div8.textContent = "a-=++b : a = " + a + " b = " + b;
b = 2;
a = 1;
a += b--;
div9.textContent = "a+=b-- : a = " + a + " b = " + b;
b = 2;
a = 1;
a += --b;
div10.textContent = "a+=--b : a = " + a + " b = " + b;